// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVh3sCrLHRrrXwEGrtLFdprUN0JsCkJSU',
    appId: '1:300035165281:web:86badec42a47720389ae20',
    messagingSenderId: '300035165281',
    projectId: 'yatra-c40f5',
    authDomain: 'yatra-c40f5.firebaseapp.com',
    storageBucket: 'yatra-c40f5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC82zKrcMTW-Smzut10gPRHUBpa-H4HIfs',
    appId: '1:300035165281:android:47671a16421f324689ae20',
    messagingSenderId: '300035165281',
    projectId: 'yatra-c40f5',
    storageBucket: 'yatra-c40f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpZVANjjQA0xNxTsmxh3eBSNR5IbOiS2w',
    appId: '1:300035165281:ios:3af330064d2bad8f89ae20',
    messagingSenderId: '300035165281',
    projectId: 'yatra-c40f5',
    storageBucket: 'yatra-c40f5.firebasestorage.app',
    iosBundleId: 'com.yatra.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpZVANjjQA0xNxTsmxh3eBSNR5IbOiS2w',
    appId: '1:300035165281:ios:84e025f5812f6cb989ae20',
    messagingSenderId: '300035165281',
    projectId: 'yatra-c40f5',
    storageBucket: 'yatra-c40f5.firebasestorage.app',
    iosBundleId: 'com.example.yatra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVh3sCrLHRrrXwEGrtLFdprUN0JsCkJSU',
    appId: '1:300035165281:web:4a64bf06e696aec489ae20',
    messagingSenderId: '300035165281',
    projectId: 'yatra-c40f5',
    authDomain: 'yatra-c40f5.firebaseapp.com',
    storageBucket: 'yatra-c40f5.firebasestorage.app',
  );
}
